* To do
** DONE Populate relations present in the import statement
   CLOSED: [2019-03-01 Fri 18:07]
Add to the relations that are referred by the parameters. The other approach is to erase the content of the existing relations. However, this latter approach is not monotonic and requires care during stratification.

Using different IDs for AST nodes from different programs to allow concatenation of programs without mixing AST nodes.
** DONE Pretty print the program
   CLOSED: [2019-03-01 Fri 18:17]
Add a pretty print implementation for the IMPORTLiteral AST node.

** DONE Implement a typechecker in DatalogM
   CLOSED: [2019-03-04 Mon 12:00]
The DatalogM engine typechecker is now disabled, so a new type checker written in Datalog is needed. The "!=" literal might be needed, which means that the signature of the IMPORT statement must be expanded to bring in representation of the logical and arithmetic expressions.

** TODO Use souffle for evaluation
** TODO Replace the datachecker in the DatalogM interpreted with the new one
** TODO Remove the TYPEOF special literal
** TODO Remove type constants

** TODO Introduce non-binding variable (i.e. _)
Allow the non-binding variable in negated atoms.

* Future changes
** TODO Non-referenceable built-in predicates: e.g. INPUT, OUTPUT, IMPORT, EXPORT, TYPEOF
- Disallow at grammar level.

* Questions
** Do we really need types?
- Can we replace types with strings?
- Update the TYPEOF predicate such that it does not use lists

** Can we write a datalog program that typechecks itself?
