/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig;

public class map_string_string {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected map_string_string(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(map_string_string obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigInterfaceJNI.delete_map_string_string(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public map_string_string() {
    this(SwigInterfaceJNI.new_map_string_string__SWIG_0(), true);
  }

  public map_string_string(map_string_string arg0) {
    this(SwigInterfaceJNI.new_map_string_string__SWIG_1(map_string_string.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return SwigInterfaceJNI.map_string_string_size(swigCPtr, this);
  }

  public boolean empty() {
    return SwigInterfaceJNI.map_string_string_empty(swigCPtr, this);
  }

  public void clear() {
    SwigInterfaceJNI.map_string_string_clear(swigCPtr, this);
  }

  public String get(String key) {
    return SwigInterfaceJNI.map_string_string_get(swigCPtr, this, key);
  }

  public void set(String key, String x) {
    SwigInterfaceJNI.map_string_string_set(swigCPtr, this, key, x);
  }

  public void del(String key) {
    SwigInterfaceJNI.map_string_string_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return SwigInterfaceJNI.map_string_string_has_key(swigCPtr, this, key);
  }

}
