/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig;

public class SWIGSouffleProgram {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SWIGSouffleProgram(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SWIGSouffleProgram obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigInterfaceJNI.delete_SWIGSouffleProgram(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGSouffleProgram(SWIGTYPE_p_souffle__SouffleProgram program) {
    this(SwigInterfaceJNI.new_SWIGSouffleProgram(SWIGTYPE_p_souffle__SouffleProgram.getCPtr(program)), true);
  }

  public void run() {
    SwigInterfaceJNI.SWIGSouffleProgram_run(swigCPtr, this);
  }

  public void runAll(String inputDirectory, String outputDirectory) {
    SwigInterfaceJNI.SWIGSouffleProgram_runAll(swigCPtr, this, inputDirectory, outputDirectory);
  }

  public void loadAll(String inputDirectory, String internalDB) {
    SwigInterfaceJNI.SWIGSouffleProgram_loadAll(swigCPtr, this, inputDirectory, internalDB);
  }

  public void printAll(String outputDirectory, String internalDB) {
    SwigInterfaceJNI.SWIGSouffleProgram_printAll(swigCPtr, this, outputDirectory, internalDB);
  }

  public void dumpInputs(SWIGTYPE_p_std__ostream out) {
    SwigInterfaceJNI.SWIGSouffleProgram_dumpInputs__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out));
  }

  public void dumpInputs() {
    SwigInterfaceJNI.SWIGSouffleProgram_dumpInputs__SWIG_1(swigCPtr, this);
  }

  public void dumpOutputs(SWIGTYPE_p_std__ostream out) {
    SwigInterfaceJNI.SWIGSouffleProgram_dumpOutputs__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out));
  }

  public void dumpOutputs() {
    SwigInterfaceJNI.SWIGSouffleProgram_dumpOutputs__SWIG_1(swigCPtr, this);
  }

  public SWIGSouffleRelation getRelation(String name) {
    long cPtr = SwigInterfaceJNI.SWIGSouffleProgram_getRelation(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGSouffleRelation(cPtr, false);
  }

  public void setNumThreads(int n) {
    SwigInterfaceJNI.SWIGSouffleProgram_setNumThreads(swigCPtr, this, n);
  }

}
