/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig;

public class SwigInterfaceJNI {
  public final static native long new_map_string_string__SWIG_0();
  public final static native long new_map_string_string__SWIG_1(long jarg1, map_string_string jarg1_);
  public final static native long map_string_string_size(long jarg1, map_string_string jarg1_);
  public final static native boolean map_string_string_empty(long jarg1, map_string_string jarg1_);
  public final static native void map_string_string_clear(long jarg1, map_string_string jarg1_);
  public final static native String map_string_string_get(long jarg1, map_string_string jarg1_, String jarg2);
  public final static native void map_string_string_set(long jarg1, map_string_string jarg1_, String jarg2, String jarg3);
  public final static native void map_string_string_del(long jarg1, map_string_string jarg1_, String jarg2);
  public final static native boolean map_string_string_has_key(long jarg1, map_string_string jarg1_, String jarg2);
  public final static native void delete_map_string_string(long jarg1);
  public final static native void SWIGSouffleTuple_add__SWIG_0(long jarg1, SWIGSouffleTuple jarg1_, long jarg2);
  public final static native void SWIGSouffleTuple_add__SWIG_1(long jarg1, SWIGSouffleTuple jarg1_, String jarg2);
  public final static native void delete_SWIGSouffleTuple(long jarg1);
  public final static native void SWIGSouffleRelation_add__SWIG_0(long jarg1, SWIGSouffleRelation jarg1_, long jarg2, SWIGSouffleTuple jarg2_);
  public final static native void SWIGSouffleRelation_add__SWIG_1(long jarg1, SWIGSouffleRelation jarg1_, String jarg2, long jarg3, long jarg4, long jarg5, String jarg6);
  public final static native void SWIGSouffleRelation_add__SWIG_2(long jarg1, SWIGSouffleRelation jarg1_, String[] jarg2, long[] jarg3, long[] jarg4, long[] jarg5, String[] jarg6, int jarg7);
  public final static native void SWIGSouffleRelation_readTuplesFromBuffer(long jarg1, SWIGSouffleRelation jarg1_, java.nio.ByteBuffer jarg2);
  public final static native long SWIGSouffleRelation_makeTuple(long jarg1, SWIGSouffleRelation jarg1_);
  public final static native void delete_SWIGSouffleRelation(long jarg1);
  public final static native long new_SWIGSouffleProgram(long jarg1);
  public final static native void delete_SWIGSouffleProgram(long jarg1);
  public final static native void SWIGSouffleProgram_run(long jarg1, SWIGSouffleProgram jarg1_);
  public final static native void SWIGSouffleProgram_runAll(long jarg1, SWIGSouffleProgram jarg1_, String jarg2, String jarg3);
  public final static native void SWIGSouffleProgram_loadAll(long jarg1, SWIGSouffleProgram jarg1_, String jarg2, String jarg3);
  public final static native void SWIGSouffleProgram_printAll(long jarg1, SWIGSouffleProgram jarg1_, String jarg2, String jarg3);
  public final static native void SWIGSouffleProgram_dumpInputs__SWIG_0(long jarg1, SWIGSouffleProgram jarg1_, long jarg2);
  public final static native void SWIGSouffleProgram_dumpInputs__SWIG_1(long jarg1, SWIGSouffleProgram jarg1_);
  public final static native void SWIGSouffleProgram_dumpOutputs__SWIG_0(long jarg1, SWIGSouffleProgram jarg1_, long jarg2);
  public final static native void SWIGSouffleProgram_dumpOutputs__SWIG_1(long jarg1, SWIGSouffleProgram jarg1_);
  public final static native long SWIGSouffleProgram_getRelation(long jarg1, SWIGSouffleProgram jarg1_, String jarg2);
  public final static native void SWIGSouffleProgram_setNumThreads(long jarg1, SWIGSouffleProgram jarg1_, int jarg2);
  public final static native long newInstance(String jarg1);
}
