/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig;

public class SWIGSouffleRelation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SWIGSouffleRelation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SWIGSouffleRelation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigInterfaceJNI.delete_SWIGSouffleRelation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void add(SWIGSouffleTuple tpl) {
    SwigInterfaceJNI.SWIGSouffleRelation_add__SWIG_0(swigCPtr, this, SWIGSouffleTuple.getCPtr(tpl), tpl);
  }

  public void add(String s0, long l1, long l2, long l3, String s4) {
    SwigInterfaceJNI.SWIGSouffleRelation_add__SWIG_1(swigCPtr, this, s0, l1, l2, l3, s4);
  }

  public void add(String[] s0, long[] l1, long[] l2, long[] l3, String[] s4, int n) {
    SwigInterfaceJNI.SWIGSouffleRelation_add__SWIG_2(swigCPtr, this, s0, l1, l2, l3, s4, n);
  }

  public void readTuplesFromBuffer(java.nio.ByteBuffer buf) {
  assert buf.isDirect() : "Buffer must be allocated direct.";
    {
      SwigInterfaceJNI.SWIGSouffleRelation_readTuplesFromBuffer(swigCPtr, this, buf);
    }
  }

  public SWIGSouffleTuple makeTuple() {
    return new SWIGSouffleTuple(SwigInterfaceJNI.SWIGSouffleRelation_makeTuple(swigCPtr, this), true);
  }

}
