/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig;

public class SWIGSouffleRelation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SWIGSouffleRelation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SWIGSouffleRelation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigInterfaceJNI.delete_SWIGSouffleRelation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void add(SWIGSouffleTuple tpl) {
    SwigInterfaceJNI.SWIGSouffleRelation_add(swigCPtr, this, SWIGSouffleTuple.getCPtr(tpl), tpl);
  }

  public SWIGSouffleTuple makeTuple() {
    long cPtr = SwigInterfaceJNI.SWIGSouffleRelation_makeTuple(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGSouffleTuple(cPtr, false);
  }

}
