/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig;

public class SWIGSouffleTuple {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SWIGSouffleTuple(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SWIGSouffleTuple obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigInterfaceJNI.delete_SWIGSouffleTuple(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void add(long v) {
    SwigInterfaceJNI.SWIGSouffleTuple_add__SWIG_0(swigCPtr, this, v);
  }

  public void add(String s) {
    SwigInterfaceJNI.SWIGSouffleTuple_add__SWIG_1(swigCPtr, this, s);
  }

}
