/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package clang.swig;

public class ClangClogBuilder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClangClogBuilder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClangClogBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clogJNI.delete_ClangClogBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ClangClogBuilder(VectorString Args) {
    this(clogJNI.new_ClangClogBuilder(VectorString.getCPtr(Args), Args), true);
  }

  public ClangClog build() {
    long cPtr = clogJNI.ClangClogBuilder_build(swigCPtr, this);
    return (cPtr == 0) ? null : new ClangClog(cPtr, false);
  }

}
