/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package clang.swig;

public class clogJNI {
  public final static native void imaxdiv_t_quot_set(long jarg1, imaxdiv_t jarg1_, int jarg2);
  public final static native int imaxdiv_t_quot_get(long jarg1, imaxdiv_t jarg1_);
  public final static native void imaxdiv_t_rem_set(long jarg1, imaxdiv_t jarg1_, int jarg2);
  public final static native int imaxdiv_t_rem_get(long jarg1, imaxdiv_t jarg1_);
  public final static native long new_imaxdiv_t();
  public final static native void delete_imaxdiv_t(long jarg1);
  public final static native int imaxabs(int jarg1);
  public final static native long imaxdiv(int jarg1, int jarg2);
  public final static native int strtoimax(String jarg1, long jarg2, int jarg3);
  public final static native long strtoumax(String jarg1, long jarg2, int jarg3);
  public final static native long new_VectorLong__SWIG_0();
  public final static native long new_VectorLong__SWIG_1(long jarg1, VectorLong jarg1_);
  public final static native long VectorLong_capacity(long jarg1, VectorLong jarg1_);
  public final static native void VectorLong_reserve(long jarg1, VectorLong jarg1_, long jarg2);
  public final static native boolean VectorLong_isEmpty(long jarg1, VectorLong jarg1_);
  public final static native void VectorLong_clear(long jarg1, VectorLong jarg1_);
  public final static native long new_VectorLong__SWIG_2(int jarg1, long jarg2);
  public final static native int VectorLong_doSize(long jarg1, VectorLong jarg1_);
  public final static native void VectorLong_doAdd__SWIG_0(long jarg1, VectorLong jarg1_, long jarg2);
  public final static native void VectorLong_doAdd__SWIG_1(long jarg1, VectorLong jarg1_, int jarg2, long jarg3);
  public final static native long VectorLong_doRemove(long jarg1, VectorLong jarg1_, int jarg2);
  public final static native long VectorLong_doGet(long jarg1, VectorLong jarg1_, int jarg2);
  public final static native long VectorLong_doSet(long jarg1, VectorLong jarg1_, int jarg2, long jarg3);
  public final static native void VectorLong_doRemoveRange(long jarg1, VectorLong jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorLong(long jarg1);
  public final static native long new_VectorVectorLong__SWIG_0();
  public final static native long new_VectorVectorLong__SWIG_1(long jarg1, VectorVectorLong jarg1_);
  public final static native long VectorVectorLong_capacity(long jarg1, VectorVectorLong jarg1_);
  public final static native void VectorVectorLong_reserve(long jarg1, VectorVectorLong jarg1_, long jarg2);
  public final static native boolean VectorVectorLong_isEmpty(long jarg1, VectorVectorLong jarg1_);
  public final static native void VectorVectorLong_clear(long jarg1, VectorVectorLong jarg1_);
  public final static native long new_VectorVectorLong__SWIG_2(int jarg1, long jarg2, VectorLong jarg2_);
  public final static native int VectorVectorLong_doSize(long jarg1, VectorVectorLong jarg1_);
  public final static native void VectorVectorLong_doAdd__SWIG_0(long jarg1, VectorVectorLong jarg1_, long jarg2, VectorLong jarg2_);
  public final static native void VectorVectorLong_doAdd__SWIG_1(long jarg1, VectorVectorLong jarg1_, int jarg2, long jarg3, VectorLong jarg3_);
  public final static native long VectorVectorLong_doRemove(long jarg1, VectorVectorLong jarg1_, int jarg2);
  public final static native long VectorVectorLong_doGet(long jarg1, VectorVectorLong jarg1_, int jarg2);
  public final static native long VectorVectorLong_doSet(long jarg1, VectorVectorLong jarg1_, int jarg2, long jarg3, VectorLong jarg3_);
  public final static native void VectorVectorLong_doRemoveRange(long jarg1, VectorVectorLong jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorVectorLong(long jarg1);
  public final static native long new_VectorString__SWIG_0();
  public final static native long new_VectorString__SWIG_1(long jarg1, VectorString jarg1_);
  public final static native long VectorString_capacity(long jarg1, VectorString jarg1_);
  public final static native void VectorString_reserve(long jarg1, VectorString jarg1_, long jarg2);
  public final static native boolean VectorString_isEmpty(long jarg1, VectorString jarg1_);
  public final static native void VectorString_clear(long jarg1, VectorString jarg1_);
  public final static native long new_VectorString__SWIG_2(int jarg1, String jarg2);
  public final static native int VectorString_doSize(long jarg1, VectorString jarg1_);
  public final static native void VectorString_doAdd__SWIG_0(long jarg1, VectorString jarg1_, String jarg2);
  public final static native void VectorString_doAdd__SWIG_1(long jarg1, VectorString jarg1_, int jarg2, String jarg3);
  public final static native String VectorString_doRemove(long jarg1, VectorString jarg1_, int jarg2);
  public final static native String VectorString_doGet(long jarg1, VectorString jarg1_, int jarg2);
  public final static native String VectorString_doSet(long jarg1, VectorString jarg1_, int jarg2, String jarg3);
  public final static native void VectorString_doRemoveRange(long jarg1, VectorString jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorString(long jarg1);
  public final static native void ClangClog_Loc_Filename_set(long jarg1, ClangClog.Loc jarg1_, String jarg2);
  public final static native String ClangClog_Loc_Filename_get(long jarg1, ClangClog.Loc jarg1_);
  public final static native void ClangClog_Loc_StartLine_set(long jarg1, ClangClog.Loc jarg1_, long jarg2);
  public final static native long ClangClog_Loc_StartLine_get(long jarg1, ClangClog.Loc jarg1_);
  public final static native void ClangClog_Loc_StartCol_set(long jarg1, ClangClog.Loc jarg1_, long jarg2);
  public final static native long ClangClog_Loc_StartCol_get(long jarg1, ClangClog.Loc jarg1_);
  public final static native void ClangClog_Loc_EndLine_set(long jarg1, ClangClog.Loc jarg1_, long jarg2);
  public final static native long ClangClog_Loc_EndLine_get(long jarg1, ClangClog.Loc jarg1_);
  public final static native void ClangClog_Loc_EndCol_set(long jarg1, ClangClog.Loc jarg1_, long jarg2);
  public final static native long ClangClog_Loc_EndCol_get(long jarg1, ClangClog.Loc jarg1_);
  public final static native long new_ClangClog_Loc__SWIG_0();
  public final static native long new_ClangClog_Loc__SWIG_1(String jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native void delete_ClangClog_Loc(long jarg1);
  public final static native long new_ClangClog(long jarg1, long jarg2, VectorString jarg2_);
  public final static native boolean ClangClog_init(long jarg1, ClangClog jarg1_);
  public final static native long ClangClog_registerMatcher(long jarg1, ClangClog jarg1_, String jarg2, boolean jarg3);
  public final static native void ClangClog_runGlobalMatchers(long jarg1, ClangClog jarg1_);
  public final static native long ClangClog_matchFromRoot(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native long ClangClog_matchFromNode(long jarg1, ClangClog jarg1_, long jarg2, long jarg3);
  public final static native long ClangClog_srcLocation(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native long ClangClog_type(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native long ClangClog_decl(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native boolean ClangClog_hasGlobalStorage(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native long ClangClog_parent(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native long ClangClog_index(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native boolean ClangClog_isParent(long jarg1, ClangClog jarg1_, long jarg2, long jarg3);
  public final static native boolean ClangClog_isAncestor(long jarg1, ClangClog jarg1_, long jarg2, long jarg3);
  public final static native String ClangClog_name(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native long ClangClog_cfg(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native long ClangClog_cfgEntry(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native long ClangClog_cfgExit(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native long ClangClog_cfgSucc(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native long ClangClog_cfgPred(long jarg1, ClangClog jarg1_, long jarg2, long jarg3);
  public final static native String ClangClog_dump(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native String ClangClog_kind(long jarg1, ClangClog jarg1_, long jarg2);
  public final static native void delete_ClangClog(long jarg1);
  public final static native long new_ClangClogBuilder(long jarg1, VectorString jarg1_);
  public final static native void delete_ClangClogBuilder(long jarg1);
  public final static native long ClangClogBuilder_build(long jarg1, ClangClogBuilder jarg1_);
}
