/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package clang.swig;

public class clog {
  public static int imaxabs(int n) {
    return clogJNI.imaxabs(n);
  }

  public static imaxdiv_t imaxdiv(int numer, int denom) {
    return new imaxdiv_t(clogJNI.imaxdiv(numer, denom), true);
  }

  public static int strtoimax(String nptr, SWIGTYPE_p_p_char endptr, int base) {
    return clogJNI.strtoimax(nptr, SWIGTYPE_p_p_char.getCPtr(endptr), base);
  }

  public static long strtoumax(String nptr, SWIGTYPE_p_p_char endptr, int base) {
    return clogJNI.strtoumax(nptr, SWIGTYPE_p_p_char.getCPtr(endptr), base);
  }

}
