/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package clang.swig;

public class imaxdiv_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected imaxdiv_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(imaxdiv_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clogJNI.delete_imaxdiv_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setQuot(int value) {
    clogJNI.imaxdiv_t_quot_set(swigCPtr, this, value);
  }

  public int getQuot() {
    return clogJNI.imaxdiv_t_quot_get(swigCPtr, this);
  }

  public void setRem(int value) {
    clogJNI.imaxdiv_t_rem_set(swigCPtr, this, value);
  }

  public int getRem() {
    return clogJNI.imaxdiv_t_rem_get(swigCPtr, this);
  }

  public imaxdiv_t() {
    this(clogJNI.new_imaxdiv_t(), true);
  }

}
