name:                Performance
version:             0.1.0.0
github:              "HampusBalldin/Performance"
license:             BSD3
author:              "Hampus Balldin"
maintainer:          "hampus.balldin@gmail.com"
copyright:           "Copyright 2018 (C)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/HampusBalldin/Performance#readme>

dependencies:
- base >= 4.7 && < 5
- process
- text
- transformers
- time
- clock
- split
- filepath
- parsec

library:
  source-dirs: src

executables:
  Performance-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Performance

tests:
  Performance-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Performance
